
server:
  port: 8766

spring:
  application:
    name: Zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 1100
  ribbon:
    ConnectTimeout: 100
    ReadTimeout: 100

  routes:
    simulation-service:
      path: /simulation/**
      serviceId: simulation
    save-service:
      path: /save/**
      serviceId: save
    statistics-service:
        path: /statistics/**
        serviceId: statistics
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 11000

