server:
  port: 8765

spring:
  application:
    name: save
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true









